#ifndef H_PRICE
#define H_PRICE

#define CITY_DISTRICT_URBAN_PRICE 50
#define CITY_DISTRICT_GENERATOR_PRICE 50
#define CITY_DISTRICT_MINING_PRICE 50
#define CITY_DISTRICT_AGRICULTURE_PRICE 50
#define CITY_BUILDING_PRICE 400

#define CITY_DISTRICT_URBAN_TIME 12
#define CITY_DISTRICT_GENERATOR_TIME 12
#define CITY_DISTRICT_MINING_TIME 12
#define CITY_DISTRICT_AGRICULTURE_TIME 12
#define CITY_BUILDING_TIME 10

#define CITY_DISTRICT_URBAN_MAX 10
#define CITY_DISTRICT_GENERATOR_MAX 10
#define CITY_DISTRICT_MINING_MAX 10
#define CITY_DISTRICT_AGRICULTURE_MAX 10
#define CITY_BUILDING_MAX 6

#endif