#ifndef var_gfx_appvar_include_file
#define var_gfx_appvar_include_file

#ifdef __cplusplus
extern "C" {
#endif

#define sizeof_gfx_pal 140
#define gfx_pal (var_gfx_appvar[0])
#define sizeof_background_gfx_pal 512
#define background_gfx_pal (var_gfx_appvar[1])
#define gfx_sprites_palette_offset 0
#define ourFleet_width 7
#define ourFleet_height 6
#define var_gfx_gfx_sprites_ourFleet_index 2
#define ourFleet ((gfx_sprite_t*)var_gfx_appvar[2])
#define alliedFleet_width 7
#define alliedFleet_height 6
#define var_gfx_gfx_sprites_alliedFleet_index 3
#define alliedFleet ((gfx_sprite_t*)var_gfx_appvar[3])
#define neutralFleet_width 7
#define neutralFleet_height 6
#define var_gfx_gfx_sprites_neutralFleet_index 4
#define neutralFleet ((gfx_sprite_t*)var_gfx_appvar[4])
#define ennemyFleet_width 7
#define ennemyFleet_height 6
#define var_gfx_gfx_sprites_ennemyFleet_index 5
#define ennemyFleet ((gfx_sprite_t*)var_gfx_appvar[5])
#define highHabitablePlanet_width 7
#define highHabitablePlanet_height 7
#define var_gfx_gfx_sprites_highHabitablePlanet_index 6
#define highHabitablePlanet ((gfx_sprite_t*)var_gfx_appvar[6])
#define lowHabitablePlanet_width 7
#define lowHabitablePlanet_height 7
#define var_gfx_gfx_sprites_lowHabitablePlanet_index 7
#define lowHabitablePlanet ((gfx_sprite_t*)var_gfx_appvar[7])
#define middleHabitablePlanet_width 7
#define middleHabitablePlanet_height 7
#define var_gfx_gfx_sprites_middleHabitablePlanet_index 8
#define middleHabitablePlanet ((gfx_sprite_t*)var_gfx_appvar[8])
#define ethic_authoritarian_width 29
#define ethic_authoritarian_height 29
#define var_gfx_gfx_sprites_ethic_authoritarian_index 9
#define ethic_authoritarian ((gfx_sprite_t*)var_gfx_appvar[9])
#define ethic_egalitarian_width 29
#define ethic_egalitarian_height 29
#define var_gfx_gfx_sprites_ethic_egalitarian_index 10
#define ethic_egalitarian ((gfx_sprite_t*)var_gfx_appvar[10])
#define ethic_fanatic_authoritarian_width 29
#define ethic_fanatic_authoritarian_height 29
#define var_gfx_gfx_sprites_ethic_fanatic_authoritarian_index 11
#define ethic_fanatic_authoritarian ((gfx_sprite_t*)var_gfx_appvar[11])
#define ethic_fanatic_egalitarian_width 29
#define ethic_fanatic_egalitarian_height 29
#define var_gfx_gfx_sprites_ethic_fanatic_egalitarian_index 12
#define ethic_fanatic_egalitarian ((gfx_sprite_t*)var_gfx_appvar[12])
#define ethic_fanatic_militarist_width 29
#define ethic_fanatic_militarist_height 29
#define var_gfx_gfx_sprites_ethic_fanatic_militarist_index 13
#define ethic_fanatic_militarist ((gfx_sprite_t*)var_gfx_appvar[13])
#define ethic_fanatic_materialist_width 29
#define ethic_fanatic_materialist_height 29
#define var_gfx_gfx_sprites_ethic_fanatic_materialist_index 14
#define ethic_fanatic_materialist ((gfx_sprite_t*)var_gfx_appvar[14])
#define ethic_fanatic_pacifist_width 29
#define ethic_fanatic_pacifist_height 29
#define var_gfx_gfx_sprites_ethic_fanatic_pacifist_index 15
#define ethic_fanatic_pacifist ((gfx_sprite_t*)var_gfx_appvar[15])
#define ethic_fanatic_spiritualists_width 29
#define ethic_fanatic_spiritualists_height 29
#define var_gfx_gfx_sprites_ethic_fanatic_spiritualists_index 16
#define ethic_fanatic_spiritualists ((gfx_sprite_t*)var_gfx_appvar[16])
#define ethic_fanatic_xenophile_width 29
#define ethic_fanatic_xenophile_height 29
#define var_gfx_gfx_sprites_ethic_fanatic_xenophile_index 17
#define ethic_fanatic_xenophile ((gfx_sprite_t*)var_gfx_appvar[17])
#define ethic_fanatic_xenophobe_width 29
#define ethic_fanatic_xenophobe_height 29
#define var_gfx_gfx_sprites_ethic_fanatic_xenophobe_index 18
#define ethic_fanatic_xenophobe ((gfx_sprite_t*)var_gfx_appvar[18])
#define ethic_gestalt_consciousness_width 29
#define ethic_gestalt_consciousness_height 29
#define var_gfx_gfx_sprites_ethic_gestalt_consciousness_index 19
#define ethic_gestalt_consciousness ((gfx_sprite_t*)var_gfx_appvar[19])
#define ethic_materialist_width 29
#define ethic_materialist_height 29
#define var_gfx_gfx_sprites_ethic_materialist_index 20
#define ethic_materialist ((gfx_sprite_t*)var_gfx_appvar[20])
#define ethic_militarist_width 29
#define ethic_militarist_height 29
#define var_gfx_gfx_sprites_ethic_militarist_index 21
#define ethic_militarist ((gfx_sprite_t*)var_gfx_appvar[21])
#define ethic_pacifist_width 29
#define ethic_pacifist_height 29
#define var_gfx_gfx_sprites_ethic_pacifist_index 22
#define ethic_pacifist ((gfx_sprite_t*)var_gfx_appvar[22])
#define ethic_choice_width 29
#define ethic_choice_height 29
#define var_gfx_gfx_sprites_ethic_choice_index 23
#define ethic_choice ((gfx_sprite_t*)var_gfx_appvar[23])
#define ethic_selected_width 29
#define ethic_selected_height 29
#define var_gfx_gfx_sprites_ethic_selected_index 24
#define ethic_selected ((gfx_sprite_t*)var_gfx_appvar[24])
#define ethic_spiritualists_width 29
#define ethic_spiritualists_height 29
#define var_gfx_gfx_sprites_ethic_spiritualists_index 25
#define ethic_spiritualists ((gfx_sprite_t*)var_gfx_appvar[25])
#define ethic_xenophile_width 29
#define ethic_xenophile_height 29
#define var_gfx_gfx_sprites_ethic_xenophile_index 26
#define ethic_xenophile ((gfx_sprite_t*)var_gfx_appvar[26])
#define ethic_xenophobe_width 29
#define ethic_xenophobe_height 29
#define var_gfx_gfx_sprites_ethic_xenophobe_index 27
#define ethic_xenophobe ((gfx_sprite_t*)var_gfx_appvar[27])
#define credit_width 7
#define credit_height 11
#define var_gfx_gfx_sprites_credit_index 28
#define credit ((gfx_sprite_t*)var_gfx_appvar[28])
#define minerai_width 11
#define minerai_height 11
#define var_gfx_gfx_sprites_minerai_index 29
#define minerai ((gfx_sprite_t*)var_gfx_appvar[29])
#define food_width 9
#define food_height 11
#define var_gfx_gfx_sprites_food_index 30
#define food ((gfx_sprite_t*)var_gfx_appvar[30])
#define fer_width 12
#define fer_height 10
#define var_gfx_gfx_sprites_fer_index 31
#define fer ((gfx_sprite_t*)var_gfx_appvar[31])
#define force_our_width 3
#define force_our_height 3
#define var_gfx_gfx_sprites_force_our_index 32
#define force_our ((gfx_sprite_t*)var_gfx_appvar[32])
#define force_neutral_width 3
#define force_neutral_height 3
#define var_gfx_gfx_sprites_force_neutral_index 33
#define force_neutral ((gfx_sprite_t*)var_gfx_appvar[33])
#define force_ennemy_width 3
#define force_ennemy_height 3
#define var_gfx_gfx_sprites_force_ennemy_index 34
#define force_ennemy ((gfx_sprite_t*)var_gfx_appvar[34])
#define force_allied_width 3
#define force_allied_height 3
#define var_gfx_gfx_sprites_force_allied_index 35
#define force_allied ((gfx_sprite_t*)var_gfx_appvar[35])
#define contact_width 9
#define contact_height 9
#define var_gfx_gfx_sprites_contact_index 36
#define contact ((gfx_sprite_t*)var_gfx_appvar[36])
#define science_width 9
#define science_height 10
#define var_gfx_gfx_sprites_science_index 37
#define science ((gfx_sprite_t*)var_gfx_appvar[37])
#define market_icon_width 7
#define market_icon_height 7
#define var_gfx_gfx_sprites_market_icon_index 38
#define market_icon ((gfx_sprite_t*)var_gfx_appvar[38])
#define construction_ship_allied_icon_width 5
#define construction_ship_allied_icon_height 5
#define var_gfx_gfx_sprites_construction_ship_allied_icon_index 39
#define construction_ship_allied_icon ((gfx_sprite_t*)var_gfx_appvar[39])
#define construction_ship_our_icon_width 5
#define construction_ship_our_icon_height 5
#define var_gfx_gfx_sprites_construction_ship_our_icon_index 40
#define construction_ship_our_icon ((gfx_sprite_t*)var_gfx_appvar[40])
#define construction_ship_neutral_icon_width 5
#define construction_ship_neutral_icon_height 5
#define var_gfx_gfx_sprites_construction_ship_neutral_icon_index 41
#define construction_ship_neutral_icon ((gfx_sprite_t*)var_gfx_appvar[41])
#define construction_ship_ennemy_icon_width 5
#define construction_ship_ennemy_icon_height 5
#define var_gfx_gfx_sprites_construction_ship_ennemy_icon_index 42
#define construction_ship_ennemy_icon ((gfx_sprite_t*)var_gfx_appvar[42])
#define science_ship_allied_icon_width 5
#define science_ship_allied_icon_height 5
#define var_gfx_gfx_sprites_science_ship_allied_icon_index 43
#define science_ship_allied_icon ((gfx_sprite_t*)var_gfx_appvar[43])
#define science_ship_our_icon_width 5
#define science_ship_our_icon_height 5
#define var_gfx_gfx_sprites_science_ship_our_icon_index 44
#define science_ship_our_icon ((gfx_sprite_t*)var_gfx_appvar[44])
#define science_ship_neutral_icon_width 5
#define science_ship_neutral_icon_height 5
#define var_gfx_gfx_sprites_science_ship_neutral_icon_index 45
#define science_ship_neutral_icon ((gfx_sprite_t*)var_gfx_appvar[45])
#define science_ship_ennemy_icon_width 5
#define science_ship_ennemy_icon_height 5
#define var_gfx_gfx_sprites_science_ship_ennemy_icon_index 46
#define science_ship_ennemy_icon ((gfx_sprite_t*)var_gfx_appvar[46])
#define pop_icon_width 4
#define pop_icon_height 7
#define var_gfx_gfx_sprites_pop_icon_index 47
#define pop_icon ((gfx_sprite_t*)var_gfx_appvar[47])
#define free_job_icon_width 4
#define free_job_icon_height 7
#define var_gfx_gfx_sprites_free_job_icon_index 48
#define free_job_icon ((gfx_sprite_t*)var_gfx_appvar[48])
#define criminality_pop_icon_width 4
#define criminality_pop_icon_height 7
#define var_gfx_gfx_sprites_criminality_pop_icon_index 49
#define criminality_pop_icon ((gfx_sprite_t*)var_gfx_appvar[49])
#define free_houses_icon_width 6
#define free_houses_icon_height 6
#define var_gfx_gfx_sprites_free_houses_icon_index 50
#define free_houses_icon ((gfx_sprite_t*)var_gfx_appvar[50])
#define amienties_icon_width 5
#define amienties_icon_height 4
#define var_gfx_gfx_sprites_amienties_icon_index 51
#define amienties_icon ((gfx_sprite_t*)var_gfx_appvar[51])
#define unemployed_pop_icon_width 7
#define unemployed_pop_icon_height 7
#define var_gfx_gfx_sprites_unemployed_pop_icon_index 52
#define unemployed_pop_icon ((gfx_sprite_t*)var_gfx_appvar[52])
#define opinion_icon_width 10
#define opinion_icon_height 10
#define var_gfx_gfx_sprites_opinion_icon_index 53
#define opinion_icon ((gfx_sprite_t*)var_gfx_appvar[53])
#define leader_clothes_1_width 13
#define leader_clothes_1_height 9
#define var_gfx_gfx_sprites_leader_clothes_1_index 54
#define leader_clothes_1 ((gfx_sprite_t*)var_gfx_appvar[54])
#define leader_clothes_2_width 13
#define leader_clothes_2_height 11
#define var_gfx_gfx_sprites_leader_clothes_2_index 55
#define leader_clothes_2 ((gfx_sprite_t*)var_gfx_appvar[55])
#define leader_clothes_3_width 14
#define leader_clothes_3_height 9
#define var_gfx_gfx_sprites_leader_clothes_3_index 56
#define leader_clothes_3 ((gfx_sprite_t*)var_gfx_appvar[56])
#define leader_head_human_width 7
#define leader_head_human_height 8
#define var_gfx_gfx_sprites_leader_head_human_index 57
#define leader_head_human ((gfx_sprite_t*)var_gfx_appvar[57])
#define leader_head_mammalian_width 12
#define leader_head_mammalian_height 8
#define var_gfx_gfx_sprites_leader_head_mammalian_index 58
#define leader_head_mammalian ((gfx_sprite_t*)var_gfx_appvar[58])
#define leader_head_molluscoid_width 12
#define leader_head_molluscoid_height 10
#define var_gfx_gfx_sprites_leader_head_molluscoid_index 59
#define leader_head_molluscoid ((gfx_sprite_t*)var_gfx_appvar[59])
#define leader_head_reptilian_width 8
#define leader_head_reptilian_height 9
#define var_gfx_gfx_sprites_leader_head_reptilian_index 60
#define leader_head_reptilian ((gfx_sprite_t*)var_gfx_appvar[60])
#define blindage_icon_width 5
#define blindage_icon_height 5
#define var_gfx_gfx_sprites_blindage_icon_index 61
#define blindage_icon ((gfx_sprite_t*)var_gfx_appvar[61])
#define bouclier_icon_width 5
#define bouclier_icon_height 6
#define var_gfx_gfx_sprites_bouclier_icon_index 62
#define bouclier_icon ((gfx_sprite_t*)var_gfx_appvar[62])
#define life_icon_width 5
#define life_icon_height 5
#define var_gfx_gfx_sprites_life_icon_index 63
#define life_icon ((gfx_sprite_t*)var_gfx_appvar[63])
#define fleet_power_icon_width 4
#define fleet_power_icon_height 5
#define var_gfx_gfx_sprites_fleet_power_icon_index 64
#define fleet_power_icon ((gfx_sprite_t*)var_gfx_appvar[64])
#define low_ressources_icon_width 14
#define low_ressources_icon_height 14
#define var_gfx_gfx_sprites_low_ressources_icon_index 65
#define low_ressources_icon ((gfx_sprite_t*)var_gfx_appvar[65])
#define attitude_icon_width 10
#define attitude_icon_height 10
#define var_gfx_gfx_sprites_attitude_icon_index 66
#define attitude_icon ((gfx_sprite_t*)var_gfx_appvar[66])
#define up_icon_width 5
#define up_icon_height 8
#define var_gfx_gfx_sprites_up_icon_index 67
#define up_icon ((gfx_sprite_t*)var_gfx_appvar[67])
#define down_icon_width 5
#define down_icon_height 8
#define var_gfx_gfx_sprites_down_icon_index 68
#define down_icon ((gfx_sprite_t*)var_gfx_appvar[68])
#define pact_icon_width 10
#define pact_icon_height 9
#define var_gfx_gfx_sprites_pact_icon_index 69
#define pact_icon ((gfx_sprite_t*)var_gfx_appvar[69])
#define insult_icon_width 7
#define insult_icon_height 5
#define var_gfx_gfx_sprites_insult_icon_index 70
#define insult_icon ((gfx_sprite_t*)var_gfx_appvar[70])
#define background_gfx_sprites_palette_offset 0
#define backgroundStation_width 35
#define backgroundStation_height 25
#define var_gfx_background_gfx_sprites_backgroundStation_compressed_index 71
#define backgroundStation_compressed var_gfx_appvar[71]
#define background0_tile_width 80
#define background0_tile_height 80
#define background0_compressed var_gfx_appvar[72]
#define background0_tiles_num 1
extern unsigned char *background0_tiles_compressed[1];
#define background0_tile_0_compressed background0_tiles_compressed[0]
#define background1_tile_width 80
#define background1_tile_height 80
#define background1_compressed var_gfx_appvar[73]
#define background1_tiles_num 1
extern unsigned char *background1_tiles_compressed[1];
#define background1_tile_0_compressed background1_tiles_compressed[0]
#define background2_tile_width 80
#define background2_tile_height 80
#define background2_compressed var_gfx_appvar[74]
#define background2_tiles_num 1
extern unsigned char *background2_tiles_compressed[1];
#define background2_tile_0_compressed background2_tiles_compressed[0]
#define background3_tile_width 80
#define background3_tile_height 80
#define background3_compressed var_gfx_appvar[75]
#define background3_tiles_num 1
extern unsigned char *background3_tiles_compressed[1];
#define background3_tile_0_compressed background3_tiles_compressed[0]
#define background4_tile_width 80
#define background4_tile_height 80
#define background4_compressed var_gfx_appvar[76]
#define background4_tiles_num 1
extern unsigned char *background4_tiles_compressed[1];
#define background4_tile_0_compressed background4_tiles_compressed[0]
#define background5_tile_width 80
#define background5_tile_height 80
#define background5_compressed var_gfx_appvar[77]
#define background5_tiles_num 1
extern unsigned char *background5_tiles_compressed[1];
#define background5_tile_0_compressed background5_tiles_compressed[0]
#define background6_tile_width 80
#define background6_tile_height 80
#define background6_compressed var_gfx_appvar[78]
#define background6_tiles_num 1
extern unsigned char *background6_tiles_compressed[1];
#define background6_tile_0_compressed background6_tiles_compressed[0]
#define background7_tile_width 80
#define background7_tile_height 80
#define background7_compressed var_gfx_appvar[79]
#define background7_tiles_num 1
extern unsigned char *background7_tiles_compressed[1];
#define background7_tile_0_compressed background7_tiles_compressed[0]
#define background8_tile_width 80
#define background8_tile_height 80
#define background8_compressed var_gfx_appvar[80]
#define background8_tiles_num 1
extern unsigned char *background8_tiles_compressed[1];
#define background8_tile_0_compressed background8_tiles_compressed[0]
#define background9_tile_width 80
#define background9_tile_height 80
#define background9_compressed var_gfx_appvar[81]
#define background9_tiles_num 1
extern unsigned char *background9_tiles_compressed[1];
#define background9_tile_0_compressed background9_tiles_compressed[0]
#define background10_tile_width 80
#define background10_tile_height 80
#define background10_compressed var_gfx_appvar[82]
#define background10_tiles_num 1
extern unsigned char *background10_tiles_compressed[1];
#define background10_tile_0_compressed background10_tiles_compressed[0]
#define background11_tile_width 80
#define background11_tile_height 80
#define background11_compressed var_gfx_appvar[83]
#define background11_tiles_num 1
extern unsigned char *background11_tiles_compressed[1];
#define background11_tile_0_compressed background11_tiles_compressed[0]
#define var_gfx_entries_num 84
extern unsigned char *var_gfx_appvar[84];
unsigned char var_gfx_init(void);

#ifdef __cplusplus
}
#endif

#endif
