#ifndef var_gfx_appvar_include_file
#define var_gfx_appvar_include_file

#ifdef __cplusplus
extern "C" {
#endif

#define sizeof_gfx_pal 148
#define gfx_pal (var_gfx_appvar[0])
#define sizeof_background_gfx_pal 512
#define background_gfx_pal (var_gfx_appvar[1])
#define gfx_sprites_palette_offset 0
#define ethic_authoritarian_width 29
#define ethic_authoritarian_height 29
#define var_gfx_gfx_sprites_ethic_authoritarian_index 2
#define ethic_authoritarian ((gfx_sprite_t*)var_gfx_appvar[2])
#define ethic_choice_width 29
#define ethic_choice_height 29
#define var_gfx_gfx_sprites_ethic_choice_index 3
#define ethic_choice ((gfx_sprite_t*)var_gfx_appvar[3])
#define ethic_egalitarian_width 29
#define ethic_egalitarian_height 29
#define var_gfx_gfx_sprites_ethic_egalitarian_index 4
#define ethic_egalitarian ((gfx_sprite_t*)var_gfx_appvar[4])
#define ethic_fanatic_authoritarian_width 29
#define ethic_fanatic_authoritarian_height 29
#define var_gfx_gfx_sprites_ethic_fanatic_authoritarian_index 5
#define ethic_fanatic_authoritarian ((gfx_sprite_t*)var_gfx_appvar[5])
#define ethic_fanatic_egalitarian_width 29
#define ethic_fanatic_egalitarian_height 29
#define var_gfx_gfx_sprites_ethic_fanatic_egalitarian_index 6
#define ethic_fanatic_egalitarian ((gfx_sprite_t*)var_gfx_appvar[6])
#define ethic_fanatic_materialist_width 29
#define ethic_fanatic_materialist_height 29
#define var_gfx_gfx_sprites_ethic_fanatic_materialist_index 7
#define ethic_fanatic_materialist ((gfx_sprite_t*)var_gfx_appvar[7])
#define ethic_fanatic_militarist_width 29
#define ethic_fanatic_militarist_height 29
#define var_gfx_gfx_sprites_ethic_fanatic_militarist_index 8
#define ethic_fanatic_militarist ((gfx_sprite_t*)var_gfx_appvar[8])
#define ethic_fanatic_pacifist_width 29
#define ethic_fanatic_pacifist_height 29
#define var_gfx_gfx_sprites_ethic_fanatic_pacifist_index 9
#define ethic_fanatic_pacifist ((gfx_sprite_t*)var_gfx_appvar[9])
#define ethic_fanatic_spiritualists_width 29
#define ethic_fanatic_spiritualists_height 29
#define var_gfx_gfx_sprites_ethic_fanatic_spiritualists_index 10
#define ethic_fanatic_spiritualists ((gfx_sprite_t*)var_gfx_appvar[10])
#define ethic_fanatic_xenophile_width 29
#define ethic_fanatic_xenophile_height 29
#define var_gfx_gfx_sprites_ethic_fanatic_xenophile_index 11
#define ethic_fanatic_xenophile ((gfx_sprite_t*)var_gfx_appvar[11])
#define ethic_fanatic_xenophobe_width 29
#define ethic_fanatic_xenophobe_height 29
#define var_gfx_gfx_sprites_ethic_fanatic_xenophobe_index 12
#define ethic_fanatic_xenophobe ((gfx_sprite_t*)var_gfx_appvar[12])
#define ethic_gestalt_consciousness_width 29
#define ethic_gestalt_consciousness_height 29
#define var_gfx_gfx_sprites_ethic_gestalt_consciousness_index 13
#define ethic_gestalt_consciousness ((gfx_sprite_t*)var_gfx_appvar[13])
#define ethic_materialist_width 29
#define ethic_materialist_height 29
#define var_gfx_gfx_sprites_ethic_materialist_index 14
#define ethic_materialist ((gfx_sprite_t*)var_gfx_appvar[14])
#define ethic_militarist_width 29
#define ethic_militarist_height 29
#define var_gfx_gfx_sprites_ethic_militarist_index 15
#define ethic_militarist ((gfx_sprite_t*)var_gfx_appvar[15])
#define ethic_pacifist_width 29
#define ethic_pacifist_height 29
#define var_gfx_gfx_sprites_ethic_pacifist_index 16
#define ethic_pacifist ((gfx_sprite_t*)var_gfx_appvar[16])
#define ethic_selected_width 29
#define ethic_selected_height 29
#define var_gfx_gfx_sprites_ethic_selected_index 17
#define ethic_selected ((gfx_sprite_t*)var_gfx_appvar[17])
#define ethic_spiritualists_width 29
#define ethic_spiritualists_height 29
#define var_gfx_gfx_sprites_ethic_spiritualists_index 18
#define ethic_spiritualists ((gfx_sprite_t*)var_gfx_appvar[18])
#define ethic_xenophile_width 29
#define ethic_xenophile_height 29
#define var_gfx_gfx_sprites_ethic_xenophile_index 19
#define ethic_xenophile ((gfx_sprite_t*)var_gfx_appvar[19])
#define ethic_xenophobe_width 29
#define ethic_xenophobe_height 29
#define var_gfx_gfx_sprites_ethic_xenophobe_index 20
#define ethic_xenophobe ((gfx_sprite_t*)var_gfx_appvar[20])
#define icon_agreement_width 10
#define icon_agreement_height 9
#define var_gfx_gfx_sprites_icon_agreement_index 21
#define icon_agreement ((gfx_sprite_t*)var_gfx_appvar[21])
#define icon_alloy_width 12
#define icon_alloy_height 10
#define var_gfx_gfx_sprites_icon_alloy_index 22
#define icon_alloy ((gfx_sprite_t*)var_gfx_appvar[22])
#define icon_amienties_width 5
#define icon_amienties_height 4
#define var_gfx_gfx_sprites_icon_amienties_index 23
#define icon_amienties ((gfx_sprite_t*)var_gfx_appvar[23])
#define icon_attitude_width 10
#define icon_attitude_height 10
#define var_gfx_gfx_sprites_icon_attitude_index 24
#define icon_attitude ((gfx_sprite_t*)var_gfx_appvar[24])
#define icon_contact_width 9
#define icon_contact_height 9
#define var_gfx_gfx_sprites_icon_contact_index 25
#define icon_contact ((gfx_sprite_t*)var_gfx_appvar[25])
#define icon_credit_width 7
#define icon_credit_height 11
#define var_gfx_gfx_sprites_icon_credit_index 26
#define icon_credit ((gfx_sprite_t*)var_gfx_appvar[26])
#define icon_down_width 5
#define icon_down_height 8
#define var_gfx_gfx_sprites_icon_down_index 27
#define icon_down ((gfx_sprite_t*)var_gfx_appvar[27])
#define icon_fleetPower_width 4
#define icon_fleetPower_height 5
#define var_gfx_gfx_sprites_icon_fleetPower_index 28
#define icon_fleetPower ((gfx_sprite_t*)var_gfx_appvar[28])
#define icon_fleet_allied_width 7
#define icon_fleet_allied_height 6
#define var_gfx_gfx_sprites_icon_fleet_allied_index 29
#define icon_fleet_allied ((gfx_sprite_t*)var_gfx_appvar[29])
#define icon_fleet_ennemy_width 7
#define icon_fleet_ennemy_height 6
#define var_gfx_gfx_sprites_icon_fleet_ennemy_index 30
#define icon_fleet_ennemy ((gfx_sprite_t*)var_gfx_appvar[30])
#define icon_fleet_neutral_width 7
#define icon_fleet_neutral_height 6
#define var_gfx_gfx_sprites_icon_fleet_neutral_index 31
#define icon_fleet_neutral ((gfx_sprite_t*)var_gfx_appvar[31])
#define icon_fleet_our_width 7
#define icon_fleet_our_height 6
#define var_gfx_gfx_sprites_icon_fleet_our_index 32
#define icon_fleet_our ((gfx_sprite_t*)var_gfx_appvar[32])
#define icon_food_width 9
#define icon_food_height 11
#define var_gfx_gfx_sprites_icon_food_index 33
#define icon_food ((gfx_sprite_t*)var_gfx_appvar[33])
#define icon_freeHouse_width 6
#define icon_freeHouse_height 6
#define var_gfx_gfx_sprites_icon_freeHouse_index 34
#define icon_freeHouse ((gfx_sprite_t*)var_gfx_appvar[34])
#define icon_freeJob_width 4
#define icon_freeJob_height 7
#define var_gfx_gfx_sprites_icon_freeJob_index 35
#define icon_freeJob ((gfx_sprite_t*)var_gfx_appvar[35])
#define icon_hull_width 5
#define icon_hull_height 5
#define var_gfx_gfx_sprites_icon_hull_index 36
#define icon_hull ((gfx_sprite_t*)var_gfx_appvar[36])
#define icon_insult_width 7
#define icon_insult_height 5
#define var_gfx_gfx_sprites_icon_insult_index 37
#define icon_insult ((gfx_sprite_t*)var_gfx_appvar[37])
#define icon_life_width 5
#define icon_life_height 5
#define var_gfx_gfx_sprites_icon_life_index 38
#define icon_life ((gfx_sprite_t*)var_gfx_appvar[38])
#define icon_low_ressources_width 14
#define icon_low_ressources_height 14
#define var_gfx_gfx_sprites_icon_low_ressources_index 39
#define icon_low_ressources ((gfx_sprite_t*)var_gfx_appvar[39])
#define icon_market_width 7
#define icon_market_height 7
#define var_gfx_gfx_sprites_icon_market_index 40
#define icon_market ((gfx_sprite_t*)var_gfx_appvar[40])
#define icon_mineral_width 11
#define icon_mineral_height 11
#define var_gfx_gfx_sprites_icon_mineral_index 41
#define icon_mineral ((gfx_sprite_t*)var_gfx_appvar[41])
#define icon_notification_width 7
#define icon_notification_height 10
#define var_gfx_gfx_sprites_icon_notification_index 42
#define icon_notification ((gfx_sprite_t*)var_gfx_appvar[42])
#define icon_opinion_width 10
#define icon_opinion_height 10
#define var_gfx_gfx_sprites_icon_opinion_index 43
#define icon_opinion ((gfx_sprite_t*)var_gfx_appvar[43])
#define icon_planet_capital_width 5
#define icon_planet_capital_height 6
#define var_gfx_gfx_sprites_icon_planet_capital_index 44
#define icon_planet_capital ((gfx_sprite_t*)var_gfx_appvar[44])
#define icon_planet_green_width 7
#define icon_planet_green_height 7
#define var_gfx_gfx_sprites_icon_planet_green_index 45
#define icon_planet_green ((gfx_sprite_t*)var_gfx_appvar[45])
#define icon_planet_lab_width 4
#define icon_planet_lab_height 6
#define var_gfx_gfx_sprites_icon_planet_lab_index 46
#define icon_planet_lab ((gfx_sprite_t*)var_gfx_appvar[46])
#define icon_planet_red_width 7
#define icon_planet_red_height 7
#define var_gfx_gfx_sprites_icon_planet_red_index 47
#define icon_planet_red ((gfx_sprite_t*)var_gfx_appvar[47])
#define icon_planet_yellow_width 7
#define icon_planet_yellow_height 7
#define var_gfx_gfx_sprites_icon_planet_yellow_index 48
#define icon_planet_yellow ((gfx_sprite_t*)var_gfx_appvar[48])
#define icon_pop_width 4
#define icon_pop_height 7
#define var_gfx_gfx_sprites_icon_pop_index 49
#define icon_pop ((gfx_sprite_t*)var_gfx_appvar[49])
#define icon_pop_criminal_width 4
#define icon_pop_criminal_height 7
#define var_gfx_gfx_sprites_icon_pop_criminal_index 50
#define icon_pop_criminal ((gfx_sprite_t*)var_gfx_appvar[50])
#define icon_pop_unemployed_width 7
#define icon_pop_unemployed_height 7
#define var_gfx_gfx_sprites_icon_pop_unemployed_index 51
#define icon_pop_unemployed ((gfx_sprite_t*)var_gfx_appvar[51])
#define icon_science_width 9
#define icon_science_height 10
#define var_gfx_gfx_sprites_icon_science_index 52
#define icon_science ((gfx_sprite_t*)var_gfx_appvar[52])
#define icon_shield_width 5
#define icon_shield_height 6
#define var_gfx_gfx_sprites_icon_shield_index 53
#define icon_shield ((gfx_sprite_t*)var_gfx_appvar[53])
#define icon_ship_construction_allied_width 5
#define icon_ship_construction_allied_height 5
#define var_gfx_gfx_sprites_icon_ship_construction_allied_index 54
#define icon_ship_construction_allied ((gfx_sprite_t*)var_gfx_appvar[54])
#define icon_ship_construction_ennemy_width 5
#define icon_ship_construction_ennemy_height 5
#define var_gfx_gfx_sprites_icon_ship_construction_ennemy_index 55
#define icon_ship_construction_ennemy ((gfx_sprite_t*)var_gfx_appvar[55])
#define icon_ship_construction_neutral_width 5
#define icon_ship_construction_neutral_height 5
#define var_gfx_gfx_sprites_icon_ship_construction_neutral_index 56
#define icon_ship_construction_neutral ((gfx_sprite_t*)var_gfx_appvar[56])
#define icon_ship_construction_our_width 5
#define icon_ship_construction_our_height 5
#define var_gfx_gfx_sprites_icon_ship_construction_our_index 57
#define icon_ship_construction_our ((gfx_sprite_t*)var_gfx_appvar[57])
#define icon_ship_military_allied_width 3
#define icon_ship_military_allied_height 3
#define var_gfx_gfx_sprites_icon_ship_military_allied_index 58
#define icon_ship_military_allied ((gfx_sprite_t*)var_gfx_appvar[58])
#define icon_ship_military_ennemy_width 3
#define icon_ship_military_ennemy_height 3
#define var_gfx_gfx_sprites_icon_ship_military_ennemy_index 59
#define icon_ship_military_ennemy ((gfx_sprite_t*)var_gfx_appvar[59])
#define icon_ship_military_neutral_width 3
#define icon_ship_military_neutral_height 3
#define var_gfx_gfx_sprites_icon_ship_military_neutral_index 60
#define icon_ship_military_neutral ((gfx_sprite_t*)var_gfx_appvar[60])
#define icon_ship_military_our_width 3
#define icon_ship_military_our_height 3
#define var_gfx_gfx_sprites_icon_ship_military_our_index 61
#define icon_ship_military_our ((gfx_sprite_t*)var_gfx_appvar[61])
#define icon_ship_science_allied_width 5
#define icon_ship_science_allied_height 5
#define var_gfx_gfx_sprites_icon_ship_science_allied_index 62
#define icon_ship_science_allied ((gfx_sprite_t*)var_gfx_appvar[62])
#define icon_ship_science_ennemy_width 5
#define icon_ship_science_ennemy_height 5
#define var_gfx_gfx_sprites_icon_ship_science_ennemy_index 63
#define icon_ship_science_ennemy ((gfx_sprite_t*)var_gfx_appvar[63])
#define icon_ship_science_neutral_width 5
#define icon_ship_science_neutral_height 5
#define var_gfx_gfx_sprites_icon_ship_science_neutral_index 64
#define icon_ship_science_neutral ((gfx_sprite_t*)var_gfx_appvar[64])
#define icon_ship_science_our_width 5
#define icon_ship_science_our_height 5
#define var_gfx_gfx_sprites_icon_ship_science_our_index 65
#define icon_ship_science_our ((gfx_sprite_t*)var_gfx_appvar[65])
#define icon_up_width 5
#define icon_up_height 8
#define var_gfx_gfx_sprites_icon_up_index 66
#define icon_up ((gfx_sprite_t*)var_gfx_appvar[66])
#define leader_clothes_1_width 13
#define leader_clothes_1_height 9
#define var_gfx_gfx_sprites_leader_clothes_1_index 67
#define leader_clothes_1 ((gfx_sprite_t*)var_gfx_appvar[67])
#define leader_clothes_2_width 13
#define leader_clothes_2_height 11
#define var_gfx_gfx_sprites_leader_clothes_2_index 68
#define leader_clothes_2 ((gfx_sprite_t*)var_gfx_appvar[68])
#define leader_clothes_3_width 14
#define leader_clothes_3_height 9
#define var_gfx_gfx_sprites_leader_clothes_3_index 69
#define leader_clothes_3 ((gfx_sprite_t*)var_gfx_appvar[69])
#define leader_head_human_width 7
#define leader_head_human_height 8
#define var_gfx_gfx_sprites_leader_head_human_index 70
#define leader_head_human ((gfx_sprite_t*)var_gfx_appvar[70])
#define leader_head_mammalian_width 12
#define leader_head_mammalian_height 8
#define var_gfx_gfx_sprites_leader_head_mammalian_index 71
#define leader_head_mammalian ((gfx_sprite_t*)var_gfx_appvar[71])
#define leader_head_molluscoid_width 12
#define leader_head_molluscoid_height 10
#define var_gfx_gfx_sprites_leader_head_molluscoid_index 72
#define leader_head_molluscoid ((gfx_sprite_t*)var_gfx_appvar[72])
#define leader_head_reptilian_width 8
#define leader_head_reptilian_height 9
#define var_gfx_gfx_sprites_leader_head_reptilian_index 73
#define leader_head_reptilian ((gfx_sprite_t*)var_gfx_appvar[73])
#define leader_scourge_width 20
#define leader_scourge_height 14
#define var_gfx_gfx_sprites_leader_scourge_index 74
#define leader_scourge ((gfx_sprite_t*)var_gfx_appvar[74])
#define background_gfx_sprites_palette_offset 0
#define backgroundStation_width 35
#define backgroundStation_height 25
#define var_gfx_background_gfx_sprites_backgroundStation_compressed_index 75
#define backgroundStation_compressed var_gfx_appvar[75]
#define background0_tile_width 80
#define background0_tile_height 80
#define background0_compressed var_gfx_appvar[76]
#define background0_tiles_num 1
extern unsigned char *background0_tiles_compressed[1];
#define background0_tile_0_compressed background0_tiles_compressed[0]
#define background1_tile_width 80
#define background1_tile_height 80
#define background1_compressed var_gfx_appvar[77]
#define background1_tiles_num 1
extern unsigned char *background1_tiles_compressed[1];
#define background1_tile_0_compressed background1_tiles_compressed[0]
#define background2_tile_width 80
#define background2_tile_height 80
#define background2_compressed var_gfx_appvar[78]
#define background2_tiles_num 1
extern unsigned char *background2_tiles_compressed[1];
#define background2_tile_0_compressed background2_tiles_compressed[0]
#define background3_tile_width 80
#define background3_tile_height 80
#define background3_compressed var_gfx_appvar[79]
#define background3_tiles_num 1
extern unsigned char *background3_tiles_compressed[1];
#define background3_tile_0_compressed background3_tiles_compressed[0]
#define background4_tile_width 80
#define background4_tile_height 80
#define background4_compressed var_gfx_appvar[80]
#define background4_tiles_num 1
extern unsigned char *background4_tiles_compressed[1];
#define background4_tile_0_compressed background4_tiles_compressed[0]
#define background5_tile_width 80
#define background5_tile_height 80
#define background5_compressed var_gfx_appvar[81]
#define background5_tiles_num 1
extern unsigned char *background5_tiles_compressed[1];
#define background5_tile_0_compressed background5_tiles_compressed[0]
#define background6_tile_width 80
#define background6_tile_height 80
#define background6_compressed var_gfx_appvar[82]
#define background6_tiles_num 1
extern unsigned char *background6_tiles_compressed[1];
#define background6_tile_0_compressed background6_tiles_compressed[0]
#define background7_tile_width 80
#define background7_tile_height 80
#define background7_compressed var_gfx_appvar[83]
#define background7_tiles_num 1
extern unsigned char *background7_tiles_compressed[1];
#define background7_tile_0_compressed background7_tiles_compressed[0]
#define background8_tile_width 80
#define background8_tile_height 80
#define background8_compressed var_gfx_appvar[84]
#define background8_tiles_num 1
extern unsigned char *background8_tiles_compressed[1];
#define background8_tile_0_compressed background8_tiles_compressed[0]
#define background9_tile_width 80
#define background9_tile_height 80
#define background9_compressed var_gfx_appvar[85]
#define background9_tiles_num 1
extern unsigned char *background9_tiles_compressed[1];
#define background9_tile_0_compressed background9_tiles_compressed[0]
#define background10_tile_width 80
#define background10_tile_height 80
#define background10_compressed var_gfx_appvar[86]
#define background10_tiles_num 1
extern unsigned char *background10_tiles_compressed[1];
#define background10_tile_0_compressed background10_tiles_compressed[0]
#define background11_tile_width 80
#define background11_tile_height 80
#define background11_compressed var_gfx_appvar[87]
#define background11_tiles_num 1
extern unsigned char *background11_tiles_compressed[1];
#define background11_tile_0_compressed background11_tiles_compressed[0]
#define var_gfx_entries_num 88
extern unsigned char *var_gfx_appvar[88];
unsigned char var_gfx_init(void);

#ifdef __cplusplus
}
#endif

#endif
