// convpng v7.3
// this file contains all the graphics sources for easy inclusion in a project
#ifndef __var_gfx__
#define __var_gfx__
#include <stdint.h>

#include <stdbool.h>

#define var_gfx_num 80

extern uint8_t *var_gfx[80];
#define alliedFleet_width 7
#define alliedFleet_height 6
#define alliedFleet ((gfx_sprite_t*)var_gfx[0])
#define amienties_icon_width 5
#define amienties_icon_height 4
#define amienties_icon ((gfx_sprite_t*)var_gfx[1])
#define blindage_icon_width 5
#define blindage_icon_height 5
#define blindage_icon ((gfx_sprite_t*)var_gfx[2])
#define bouclier_icon_width 5
#define bouclier_icon_height 6
#define bouclier_icon ((gfx_sprite_t*)var_gfx[3])
#define construction_ship_allied_icon_width 5
#define construction_ship_allied_icon_height 5
#define construction_ship_allied_icon ((gfx_sprite_t*)var_gfx[4])
#define construction_ship_ennemy_icon_width 5
#define construction_ship_ennemy_icon_height 5
#define construction_ship_ennemy_icon ((gfx_sprite_t*)var_gfx[5])
#define construction_ship_neutral_icon_width 5
#define construction_ship_neutral_icon_height 5
#define construction_ship_neutral_icon ((gfx_sprite_t*)var_gfx[6])
#define construction_ship_our_icon_width 5
#define construction_ship_our_icon_height 5
#define construction_ship_our_icon ((gfx_sprite_t*)var_gfx[7])
#define contact_width 9
#define contact_height 9
#define contact ((gfx_sprite_t*)var_gfx[8])
#define credit_width 7
#define credit_height 11
#define credit ((gfx_sprite_t*)var_gfx[9])
#define criminality_pop_icon_width 4
#define criminality_pop_icon_height 7
#define criminality_pop_icon ((gfx_sprite_t*)var_gfx[10])
#define ennemyFleet_width 7
#define ennemyFleet_height 6
#define ennemyFleet ((gfx_sprite_t*)var_gfx[11])
#define ethic_authoritarian_width 29
#define ethic_authoritarian_height 29
#define ethic_authoritarian ((gfx_sprite_t*)var_gfx[12])
#define ethic_choice_width 29
#define ethic_choice_height 29
#define ethic_choice ((gfx_sprite_t*)var_gfx[13])
#define ethic_egalitarian_width 29
#define ethic_egalitarian_height 29
#define ethic_egalitarian ((gfx_sprite_t*)var_gfx[14])
#define ethic_fanatic_authoritarian_width 29
#define ethic_fanatic_authoritarian_height 29
#define ethic_fanatic_authoritarian ((gfx_sprite_t*)var_gfx[15])
#define ethic_fanatic_egalitarian_width 29
#define ethic_fanatic_egalitarian_height 29
#define ethic_fanatic_egalitarian ((gfx_sprite_t*)var_gfx[16])
#define ethic_fanatic_materialist_width 29
#define ethic_fanatic_materialist_height 29
#define ethic_fanatic_materialist ((gfx_sprite_t*)var_gfx[17])
#define ethic_fanatic_militarist_width 29
#define ethic_fanatic_militarist_height 29
#define ethic_fanatic_militarist ((gfx_sprite_t*)var_gfx[18])
#define ethic_fanatic_pacifist_width 29
#define ethic_fanatic_pacifist_height 29
#define ethic_fanatic_pacifist ((gfx_sprite_t*)var_gfx[19])
#define ethic_fanatic_spiritualists_width 29
#define ethic_fanatic_spiritualists_height 29
#define ethic_fanatic_spiritualists ((gfx_sprite_t*)var_gfx[20])
#define ethic_fanatic_xenophile_width 29
#define ethic_fanatic_xenophile_height 29
#define ethic_fanatic_xenophile ((gfx_sprite_t*)var_gfx[21])
#define ethic_fanatic_xenophobe_width 29
#define ethic_fanatic_xenophobe_height 29
#define ethic_fanatic_xenophobe ((gfx_sprite_t*)var_gfx[22])
#define ethic_gestalt_consciousness_width 29
#define ethic_gestalt_consciousness_height 29
#define ethic_gestalt_consciousness ((gfx_sprite_t*)var_gfx[23])
#define ethic_materialist_width 29
#define ethic_materialist_height 29
#define ethic_materialist ((gfx_sprite_t*)var_gfx[24])
#define ethic_militarist_width 29
#define ethic_militarist_height 29
#define ethic_militarist ((gfx_sprite_t*)var_gfx[25])
#define ethic_pacifist_width 29
#define ethic_pacifist_height 29
#define ethic_pacifist ((gfx_sprite_t*)var_gfx[26])
#define ethic_selected_width 29
#define ethic_selected_height 29
#define ethic_selected ((gfx_sprite_t*)var_gfx[27])
#define ethic_spiritualists_width 29
#define ethic_spiritualists_height 29
#define ethic_spiritualists ((gfx_sprite_t*)var_gfx[28])
#define ethic_xenophile_width 29
#define ethic_xenophile_height 29
#define ethic_xenophile ((gfx_sprite_t*)var_gfx[29])
#define ethic_xenophobe_width 29
#define ethic_xenophobe_height 29
#define ethic_xenophobe ((gfx_sprite_t*)var_gfx[30])
#define fer_width 12
#define fer_height 10
#define fer ((gfx_sprite_t*)var_gfx[31])
#define fleet_power_icon_width 4
#define fleet_power_icon_height 5
#define fleet_power_icon ((gfx_sprite_t*)var_gfx[32])
#define food_width 9
#define food_height 11
#define food ((gfx_sprite_t*)var_gfx[33])
#define force_allied_width 3
#define force_allied_height 3
#define force_allied ((gfx_sprite_t*)var_gfx[34])
#define force_ennemy_width 3
#define force_ennemy_height 3
#define force_ennemy ((gfx_sprite_t*)var_gfx[35])
#define force_neutral_width 3
#define force_neutral_height 3
#define force_neutral ((gfx_sprite_t*)var_gfx[36])
#define force_our_width 3
#define force_our_height 3
#define force_our ((gfx_sprite_t*)var_gfx[37])
#define free_houses_icon_width 6
#define free_houses_icon_height 6
#define free_houses_icon ((gfx_sprite_t*)var_gfx[38])
#define free_job_icon_width 4
#define free_job_icon_height 7
#define free_job_icon ((gfx_sprite_t*)var_gfx[39])
#define highHabitablePlanet_width 7
#define highHabitablePlanet_height 7
#define highHabitablePlanet ((gfx_sprite_t*)var_gfx[40])
#define leader_clothes_1_width 13
#define leader_clothes_1_height 9
#define leader_clothes_1 ((gfx_sprite_t*)var_gfx[41])
#define leader_clothes_2_width 13
#define leader_clothes_2_height 11
#define leader_clothes_2 ((gfx_sprite_t*)var_gfx[42])
#define leader_clothes_3_width 14
#define leader_clothes_3_height 9
#define leader_clothes_3 ((gfx_sprite_t*)var_gfx[43])
#define leader_head_human_width 7
#define leader_head_human_height 8
#define leader_head_human ((gfx_sprite_t*)var_gfx[44])
#define leader_head_mammalian_width 12
#define leader_head_mammalian_height 8
#define leader_head_mammalian ((gfx_sprite_t*)var_gfx[45])
#define leader_head_molluscoid_width 12
#define leader_head_molluscoid_height 10
#define leader_head_molluscoid ((gfx_sprite_t*)var_gfx[46])
#define leader_head_reptilian_width 8
#define leader_head_reptilian_height 9
#define leader_head_reptilian ((gfx_sprite_t*)var_gfx[47])
#define leader_scourge_width 20
#define leader_scourge_height 14
#define leader_scourge ((gfx_sprite_t*)var_gfx[48])
#define life_icon_width 5
#define life_icon_height 5
#define life_icon ((gfx_sprite_t*)var_gfx[49])
#define lowHabitablePlanet_width 7
#define lowHabitablePlanet_height 7
#define lowHabitablePlanet ((gfx_sprite_t*)var_gfx[50])
#define market_icon_width 7
#define market_icon_height 7
#define market_icon ((gfx_sprite_t*)var_gfx[51])
#define middleHabitablePlanet_width 7
#define middleHabitablePlanet_height 7
#define middleHabitablePlanet ((gfx_sprite_t*)var_gfx[52])
#define minerai_width 11
#define minerai_height 11
#define minerai ((gfx_sprite_t*)var_gfx[53])
#define neutralFleet_width 7
#define neutralFleet_height 6
#define neutralFleet ((gfx_sprite_t*)var_gfx[54])
#define ourFleet_width 7
#define ourFleet_height 6
#define ourFleet ((gfx_sprite_t*)var_gfx[55])
#define planet_capital_icon_width 5
#define planet_capital_icon_height 6
#define planet_capital_icon ((gfx_sprite_t*)var_gfx[56])
#define planet_lab_icon_width 4
#define planet_lab_icon_height 6
#define planet_lab_icon ((gfx_sprite_t*)var_gfx[57])
#define pop_icon_width 4
#define pop_icon_height 7
#define pop_icon ((gfx_sprite_t*)var_gfx[58])
#define science_width 9
#define science_height 10
#define science ((gfx_sprite_t*)var_gfx[59])
#define science_ship_allied_icon_width 5
#define science_ship_allied_icon_height 5
#define science_ship_allied_icon ((gfx_sprite_t*)var_gfx[60])
#define science_ship_ennemy_icon_width 5
#define science_ship_ennemy_icon_height 5
#define science_ship_ennemy_icon ((gfx_sprite_t*)var_gfx[61])
#define science_ship_neutral_icon_width 5
#define science_ship_neutral_icon_height 5
#define science_ship_neutral_icon ((gfx_sprite_t*)var_gfx[62])
#define science_ship_our_icon_width 5
#define science_ship_our_icon_height 5
#define science_ship_our_icon ((gfx_sprite_t*)var_gfx[63])
#define unemployed_pop_icon_width 7
#define unemployed_pop_icon_height 7
#define unemployed_pop_icon ((gfx_sprite_t*)var_gfx[64])
#define background0_width 80
#define background0_height 80
#define background0_compressed ((gfx_sprite_t*)var_gfx[65])
#define background1_width 80
#define background1_height 80
#define background1_compressed ((gfx_sprite_t*)var_gfx[66])
#define background2_width 80
#define background2_height 80
#define background2_compressed ((gfx_sprite_t*)var_gfx[67])
#define background3_width 80
#define background3_height 80
#define background3_compressed ((gfx_sprite_t*)var_gfx[68])
#define background4_width 80
#define background4_height 80
#define background4_compressed ((gfx_sprite_t*)var_gfx[69])
#define background5_width 80
#define background5_height 80
#define background5_compressed ((gfx_sprite_t*)var_gfx[70])
#define background6_width 80
#define background6_height 80
#define background6_compressed ((gfx_sprite_t*)var_gfx[71])
#define background7_width 80
#define background7_height 80
#define background7_compressed ((gfx_sprite_t*)var_gfx[72])
#define background8_width 80
#define background8_height 80
#define background8_compressed ((gfx_sprite_t*)var_gfx[73])
#define background9_width 80
#define background9_height 80
#define background9_compressed ((gfx_sprite_t*)var_gfx[74])
#define background10_width 80
#define background10_height 80
#define background10_compressed ((gfx_sprite_t*)var_gfx[75])
#define background11_width 80
#define background11_height 80
#define background11_compressed ((gfx_sprite_t*)var_gfx[76])
#define backgroundStation_width 35
#define backgroundStation_height 25
#define backgroundStation_compressed ((gfx_sprite_t*)var_gfx[77])
#define notification_icon_width 7
#define notification_icon_height 10
#define notification_icon ((gfx_sprite_t*)var_gfx[78])
#define sizeof_background_gfx_pal 512
#define background_gfx_pal ((uint16_t*)var_gfx[79])
bool var_gfx_init(void);

#endif
